apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app

  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: us-central1-docker.pkg.dev/osama-project-401213/images/node-app
          ports:
            - containerPort: 3000
          env:
            - name: WEBport
              value: "3000"
            - name: DBhosts
              value: mongo-service:27017
            - name: DBuser
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: DBpass
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password

